server:
  port: 8081

spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root