spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vishalkawthale/shopping-app/tree/master/common-config

server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost